/**
 * D&D Classes Index
 * Automatically generated by split_classes.cjs
 */

import fighterData from './fighter.json';
import clericData from './cleric.json';
import rogueData from './rogue.json';
import barbarianData from './barbarian.json';
import bardData from './bard.json';
import druidData from './druid.json';
import monkData from './monk.json';
import paladinData from './paladin.json';
import rangerData from './ranger.json';
import sorcererData from './sorcerer.json';
import warlockData from './warlock.json';
import wizardData from './wizard.json';

export const classes = [
	fighterData,
	clericData,
	rogueData,
	barbarianData,
	bardData,
	druidData,
	monkData,
	paladinData,
	rangerData,
	sorcererData,
	warlockData,
	wizardData,
];
